# This file was generated by GoReleaser. DO NOT EDIT.
cask "orchard" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "93204ecd61563333343423d9c2d0674befab994a98cf0b1cff3b62b00520c9c1"
      url "https://github.com/LeafdTK/leaf/releases/download/cli%2Fv#{version}/orchard_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6b0b971cbb1641c5bdb25917e0543da8e30bed9ea36268e9a07b454f0f606af"
      url "https://github.com/LeafdTK/leaf/releases/download/cli%2Fv#{version}/orchard_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5397e91e72a712b0d1bc53f349ad98674da12e88dccd7181c502e7ba8d117acc"
      url "https://github.com/LeafdTK/leaf/releases/download/cli%2Fv#{version}/orchard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a4b76145d4ac5463530a5c8748f57506cf2dcbd6fe3dfc7ea911c166634f6eb3"
      url "https://github.com/LeafdTK/leaf/releases/download/cli%2Fv#{version}/orchard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orchard"
  desc "Orchard platform CLI"
  homepage "https://github.com/LeafdTK/leaf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orchard"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orchard"]
    end
  end

  # No zap stanza required

end
