# This file was generated by GoReleaser. DO NOT EDIT.
cask "orchard-cli" do
  version "0.18.1"

  on_macos do
    on_arm do
      sha256 "b9fb285c6172218044944a9b04389eeb3bfb06a57753d5fb34ef7481dcc2b086"
      url "https://github.com/LeafdTK/orchard-releases/releases/download/v#{version}/orchard_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a3789602fe366e0c878508f61e3c6af46e59affb9517199512e0e758b1d97689"
      url "https://github.com/LeafdTK/orchard-releases/releases/download/v#{version}/orchard_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8a86da20986650e8f53100368f30b416396292e2c60f1a8e572b4a834a47d346"
      url "https://github.com/LeafdTK/orchard-releases/releases/download/v#{version}/orchard_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "01871e3491fe2b3fac7a2549db21a502b0c9af79a38983a2de9872721be6b0f4"
      url "https://github.com/LeafdTK/orchard-releases/releases/download/v#{version}/orchard_#{version}_linux_amd64.tar.gz"
    end
  end

  name "orchard-cli"
  desc "Orchard platform CLI"
  homepage "https://github.com/hackclub/orchard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orchard"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orchard"]
    end
  end

  # No zap stanza required
end
