# This file was generated by GoReleaser. DO NOT EDIT.
cask "orchard-cli" do
  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "903423642fa5982c4bb200323cbb1007559481e9c3760cf7cafc150b6ac4ef19"
      url "https://github.com/LeafdTK/orchard-releases/releases/download/v#{version}/orchard_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b0753d3fbe4a7f60fe49ced060358495ae5c29a62318a6b8680bf2bafd1c8e42"
      url "https://github.com/LeafdTK/orchard-releases/releases/download/v#{version}/orchard_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "76cdefb3cb45498bf3ac5344549e9134b18ccf7e6a387d6b63e24f4ffe18ca87"
      url "https://github.com/LeafdTK/orchard-releases/releases/download/v#{version}/orchard_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "59b0818660eb44fe4fdac5d1caef5b23f5345fd36e791a37c6429c20417e5510"
      url "https://github.com/LeafdTK/orchard-releases/releases/download/v#{version}/orchard_#{version}_linux_amd64.tar.gz"
    end
  end

  name "orchard-cli"
  desc "Orchard platform CLI"
  homepage "https://github.com/LeafdTK/leaf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orchard"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orchard"]
    end
  end

  # No zap stanza required
end
