# This file was generated by GoReleaser. DO NOT EDIT.
cask "orchard-cli" do
  version "0.18.2"

  on_macos do
    on_arm do
      sha256 "14f16c1976f64deceea40696f524083917349b015f1ef7ce127b74d57c3faece"
      url "https://github.com/LeafdTK/orchard-releases/releases/download/v#{version}/orchard_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "67414b8e2fd6039c0df4c8368273ff1b0d426f0b82cd08ac3d28b9655281882a"
      url "https://github.com/LeafdTK/orchard-releases/releases/download/v#{version}/orchard_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "af21da31c3217ab114a186fac8eef82f1fdd7c885548d1ab7384b86e2a4f5e6a"
      url "https://github.com/LeafdTK/orchard-releases/releases/download/v#{version}/orchard_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8aeaac2d1ae34ef9021c8b777e54e47ec10f9c5947bc73da60e3eb9677cbd246"
      url "https://github.com/LeafdTK/orchard-releases/releases/download/v#{version}/orchard_#{version}_linux_amd64.tar.gz"
    end
  end

  name "orchard-cli"
  desc "Orchard platform CLI"
  homepage "https://github.com/hackclub/orchard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orchard"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orchard"]
    end
  end

  # No zap stanza required
end
